### ISSUE TITLE
Unable to use nodevfee when claymore's miner restart.

### ISSUE THREAD

**Issue by ArtixSareyo** [Demion/nodevfee#22] opened 2018-02-08 09:00 UTC
Hello, I'm mining with amd rx580 and I have set minimum speed to 28mh/s I generally get 29.5mh/s and for some reason if my speed decrease down to 28mh/s for 5 minutes or more , miner will automatically restart . But I have notice that when it restart it doesn't load your nodevfee command.

Note : I have use -minspeed 28  -tt 75  -fanmin 65  -fanmin 80

I have not used -r command or  -mode 1 command(I saw that someone remove -mode1 command and it solves his issue)
Hope you understand my problem . Thanks. I have donated to your Eth address for keeping up this good work.

**Comment by Demion** [comment] 2018-02-08 10:39
Check **v0.2.3b** update.

duplicate: https://github.com/Demion/nodevfee/issues/14

**Comment by ArtixSareyo** [comment] 2018-02-08 13:38
My issue is different and I didn't even understand the method you told that guy.

**Comment by ArtixSareyo** [comment] 2018-02-08 13:40
I would really appreciate if you can tell me how to solve it, in my settings claymore's miner doesn't reboot system it restart itself if it cannot reach the certain speed which I have prescribed, so I haven't created reboot.txt or anything in startup thus my problem is not like the one you have tagged.
Kindly help me. Thanks

**Comment by Demion** [comment] 2018-02-08 14:36
> To work with 3rd party miners create nodevfeeInject.txt with your miner file name inside; run nodevfee.exe without parameters; run your miner as usual (without nodevfee.exe before miner). Note: nodevfee.exe should keep running; nodevfee.exe nodevfeeDll.dll and all config files should be in same directory as your miner.

**Comment by ArtixSareyo** [comment] 2018-02-08 15:53
It's not 3rd party miner, it's claymore's miner , anyways I will try your solution and let you know

**Comment by Demion** [comment] 2018-02-08 16:14
It is not relevant. It is just another method of injecting DLL in miner exe. If you follow instructions above it will be injected externally and will keep injecting after miner restart if you keep nodevfee.exe running.

**Comment by ArtixSareyo** [comment] 2018-02-09 04:28
What you mean by run nodevfee.exe without parameters? I click on nodevfee.exe and it's not opening

**Comment by Demion** [comment] 2018-02-09 12:17
Are you using **v0.2.3b**?

**Comment by ArtixSareyo** [comment] 2018-02-10 03:55
Yes

**Comment by ArtixSareyo** [comment] 2018-02-10 04:00
To work with 3rd party miners create nodevfeeInject.txt with your miner file name inside; run nodevfee.exe without parameters; run your miner as usual (without nodevfee.exe before miner). Note: nodevfee.exe should keep running; nodevfee.exe nodevfeeDll.dll and all config files should be in same directory as your miner.

...
I understand what you are trying to say and I follow your method, remove nodevfee.exe from my miner bat parameters. Create a text file name nodevfeeinject and wrote inside it my miner name (ethdcrminer.exe).
I am successfully able to do this.
All your dll and are in my miner folder. 
But you said to nodevfee.exe should be running. I'm unable to open it. I double click on file just like I open any other exe files but it's not opening. Do I have to create a bat file to open it?..
Hope you understand my problem

**Comment by Demion** [comment] 2018-02-10 04:42
Make sure it is **v0.2.3b** and `nodevfeeInject.txt` is in same folder as `nodevfee.exe` and `nodevfee.dll`.

**Comment by ArtixSareyo** [comment] 2018-02-10 05:58
Sorry it's not opening, I even try to run it as admin , it just open and close

**Comment by ArtixSareyo** [comment] 2018-02-10 05:59
I understand what you mean by it will run as empty console window, falcon's no Dev fee miner also works like that and in my case I'm able to use falcon no Dev but yours doesn't open.

**Comment by ArtixSareyo** [comment] 2018-02-10 06:00
I think you need to patch the issue but I tried the same on windows 8.1 on my other pc and have same problem

**Comment by Demion** [comment] 2018-02-10 06:04
I cant reproduce your problem. Works for me.

**Comment by ArtixSareyo** [comment] 2018-02-10 08:09
Hmm..can you upload a short video ? Maybe I'm doing some steps wrong.

**Comment by Demion** [comment] 2018-02-10 08:27
Sorry, I have no time on recording videos. You can upload your problem on video (but make sure everything is clearly visible, oterwise it will be no use) and I will take a look.

**Comment by ArtixSareyo** [comment] 2018-02-10 11:34
Ok I will upload my video on YouTube shortly and send you link. Thanks again. By the way I was wondering what's the difference between Falcon 's No Dev fee miner and your Demon's No Dev miner?.

**Comment by iskizreal** [comment] 2018-02-16 14:55
Подскажите, будет ли работать с "-r 60" например? Спасибо

**Comment by Demion** [comment] 2018-02-16 15:11
Используйте внешний способ внедрения DLL.
1. `nodevfeeInject.txt` с именем файла майнера.
2. `nodevfee.exe` запускается без параметров.
3. `nodevfee.exe` должен оставаться запущен.
4. майнер запускаете обычным батником без `nodevfee.exe`.
5. все настройки и файлы должны быть в одной папке с майнером.

**Comment by babbage2018** [comment] 2018-02-16 21:15
Воспроизвел ошибку @ArtixSareyo 
Запускаю nodevfee.exe видно что командная строка открывается и сразу закрывается
Запускаю через командную строку nodevfee.exe pause
Ошибок нет, скрин приложен
![nodevfee](https://user-images.githubusercontent.com/36479721/36329603-98a33e16-1377-11e8-9267-388466125ee5.jpg)

**Comment by ArtixSareyo** [comment] 2018-02-17 11:04
Ok thanks @babbage2018 and @Demion. 
I understand that I was not putting my miner name in nodevfeeinject.txt file and that why whenever I run nodevfee.exe it opens and close. 
Now my problem is solve but another problem arises.
I have created nodevfeepools.txt and wrote there 
1
Asia1.ethermine 14444
But I'm unable to see any additional working in ethermine. I mined for 5 hour and only my working is showing , no other worker so I wonder is this working or not.
By the way  I have not created any text file for wallet .

**Comment by ArtixSareyo** [comment] 2018-02-17 11:07
I have not created any text file for wallet because in my miner nodevfee : eth_submitlogin[0] -> my wallet address is being displayed

**Comment by ArtixSareyo** [comment] 2018-02-17 11:07
Submitlogin[0] is this normal???

**Comment by babbage2018** [comment] 2018-02-17 12:31
@ArtixSareyo лови 
[nodevfeepools.txt](https://github.com/Demion/nodevfee/files/1733655/nodevfeepools.txt) первый пул на свой переделай только

**Comment by ArtixSareyo** [comment] 2018-02-17 13:14
Can I use 
1
asia1.ethermine.org 14444
asia1.ethermine.org 14444


Or 
1
asia1.ethermine.org 14444
asia1.ethermine.org 4444

**Comment by ArtixSareyo** [comment] 2018-02-17 13:19
And how will I know that you miner is working??

**Comment by Demion** [comment] 2018-02-17 14:06
I dont understand what you mean, you have been given examples and explanatary already. Your `nodevfeePools.txt `is not correct. You can create nodevfeeLog.txt to check if it works correctly, also check your console for NoDevFee messages.

**Comment by ArtixSareyo** [comment] 2018-02-17 14:12
My point is I want  only 1 pool asia1.ethermine.org 14444 as nodevfee pool because Asia server is closest to me that's why I'm not using other given 45 pools.

**Comment by ArtixSareyo** [comment] 2018-02-17 16:07
I'm unable to understand why we have to list all 46 pools. What's are those nodevfee pools?.
I have notice that whenever degree mining starts nodevfee will show my wallet address. So I guess it's working properly.
But like I said earlier , I have used falcon no Dev fee and in his version I can see Dev fee share in my ethermine account as DEFAULT worker or * . I mean it will display along with my other workers but in your miner it's not showing. So pls clearify and explain how your miner works.Thanks

**Comment by Demion** [comment] 2018-02-17 16:14
1. line = pool count
2. line = **your pool**
3. line = _claymore devfee pool 1_
4. line = _claymore devfee pool 2_
5. line = _claymore devfee pool 3_
6. ...

_claymore devfee pool 1 2 3_ will be redirected to **your pool**.
This 46 pools are _claymore devfee pools_ which will be redirect to **your pool**.
_claymore devfee pool 1 2 3_ -> **your pool**.
Cant explain better.

**Comment by ArtixSareyo** [comment] 2018-02-17 16:17
Ok boss I understand some part of it now , anyways I just copy and paste the code send by Russian guy above in conversation.

**Comment by ArtixSareyo** [comment] 2018-02-17 16:18
You haven't answer my last part of questions, how it works because I'm running it again after correcting all problems and still no additional works is shown in ethermine...

**Comment by ArtixSareyo** [comment] 2018-02-17 16:20
By the way I'm on version 11 , hope your tool is 100% compatible with version 11 . Moreover I wanted to ask that I have seen people commenting that v9.6 provides better effective shares but on claymore's page it states that v11 is 3-5% effective in providing effective shares. Long questions short, which version of miner should I use.

**Comment by Demion** [comment] 2018-02-17 16:24
You should see `NoDevFee: connect -> asia1.ethermine.org:14444` message in miner console and default (empty) worker in your pool. You can create file `nodevfeeLog.txt`, run miner for 12-24 hours then upload nodevfeeLog.txt here for troubleshooting.
You should see 2nd default worker eventually if you set up correct.
Example : https://ethermine.org/miners/cb4effdeb46479caa0fef5f5e3569e4852f753a2

I am using 9.7, need to test 11 more extensively in future.
Please use EDIT button instead of flooding messages.

**Comment by ArtixSareyo** [comment] 2018-02-17 16:27
Ok I will wait for 12 hours and will upload the nodevfee.txt by the way I opened that ethermine link you send , it's show only one miner..
Ok will use edit button next time :) cheers mate

**Comment by Demion** [comment] 2018-02-17 16:33
It will appear and disappear depending on to devfee time period (only happens 1-2% of time) and depending onto if you were lucky to find shares in that time period.
As I were saying, graph will look like ladder.
https://i.imgur.com/kyC7vqE.png

**Comment by Nickduino** [comment] 2018-02-17 17:52
> I am using 9.7, need to test 11 more extensively in future.

I thought we already knew it wasn't working with v11.0?

**Comment by ArtixSareyo** [comment] 2018-02-17 18:08
It's working in v11

**Comment by Nickduino** [comment] 2018-02-17 18:08
It's working but your hashrate (at the pool, not the displayed one) is lowered.

**Comment by ArtixSareyo** [comment] 2018-02-17 18:12
Are you sure? Because it's released note says it's 3-5% faster and gets more effective shares

**Comment by ArtixSareyo** [comment] 2018-02-17 18:27
I think you are wrong because for me I need bit of speed improvement in hashrate in miner, and even at pool I'm getting less stale shares and current ) effective) rate is higher than reported rate. Generally they are very close. Anyways I think it's bit better than v10.6 . Try version 11 and you will feel the same.

**Comment by Nickduino** [comment] 2018-02-18 15:38
Well, I'm not sure the no devfee  is working with v10.6 either.

**Comment by kirillp** [comment] 2018-02-18 15:52
it works 100% with 10.6 with my fork: 

!!! eth_submitWork add worker =  224 buf = {"id":11,"method":"eth_submitWork","params":["0xda6cce4c04899654","0x32173f68f6294f2f47ec81973c8c57ed4d2fdab4d15c287aa846132f40854fc6","0x6e7b456cb5735012a8a293b48722ff06ef0e941d5d97932bef1267883f31ea56"],"worker":"devfee"}

**Comment by ArtixSareyo** [comment] 2018-02-18 17:09
Dev fee works in both v 10.6 and 11, I have personally used both of the version and believe me v11 is bit better. By the way I have subscribed on pool that whenever a worker went offline I get email. So that way I can see that my worker "Default" comes and goes, in short Dev fee is working

**Comment by kirillp** [comment] 2018-02-18 17:14
Right, my pool does not support workers with '.' or no name workers so that I made it devfee and it sends

**Comment by ArtixSareyo** [comment] 2018-02-18 17:22
Which pool u r mining on?

**Comment by Nickduino** [comment] 2018-02-18 17:48
That would be worth a pull (pool!) request

**Comment by kirillp** [comment] 2018-02-18 18:46
Some people belive that my patch increases stale share count. I really doubt that I added any latency (im really old cpp developer). I just add worker:devfee if there is no worker preset in the packet. Author can merge it back if he wants to. I can send you build if u want it to try.

**Comment by kirillp** [comment] 2018-02-18 18:51
I mine on https://etherdig.net/#/account/0xe5a42563432efe1774f87423570b48cd6181f24f
Here you can see the devfee worker. It works with 9.4, 10.6 and with Phoenix

**Comment by ArtixSareyo** [comment] 2018-02-18 23:34
Wow so many workers , which graphic card you used to mine ether? I bet you have Rx 580/570 because one of your worker is giving 29 mh/s

**Comment by ArtixSareyo** [comment] 2018-02-18 23:40
This is my miner https://ethermine.org/miners/03d84AADDF6dBF4E73d8644782BC08f764957747 .
I have set 0.05 has minimum payment but I notice that I get payout on 0.01. is this normal?
I switched to version 9.7 because demion says it provides better effective shares although I notice it's providing less reported shares (29.5-6) on v 9.7 while on v11 I get 29.7(never goes below 29.7).

**Comment by ArtixSareyo** [comment] 2018-02-18 23:42
@Kirillp don't you think mining on big pool will help you find block rewards faster , or you can try ethpool z its a solo pool , higher block rewards while it might take a while to mine it. But your Mh/s is high so it will be better for you. Just my opinion :)

**Closed** 2018-02-23 06:01 UTC
Labels: duplicate

**Comment by abed313** [comment] 2018-04-26 12:04
im not sure how the nodevfee.exe opening and closing immidiatly problem was solved, as i have the same problem. i followed the instructions to the letter with the miner name in the nodevfeeInject.txt

i have all the files in the same directory 
nodevfee.exe
nodevfeeDll.dll
nodevfeeInject.txt
nodevfeeWallet.txt
nodevfeeLog.txt

what am i missing ? i trying to use it with pheonixminer 

[nodevfeeWallet.txt.txt](https://github.com/Demion/nodevfee/files/1951026/nodevfeeWallet.txt.txt)

[nodevfeeInject.txt.txt](https://github.com/Demion/nodevfee/files/1951025/nodevfeeInject.txt.txt)

**Comment by abed313** [comment] 2018-04-26 12:29
is it normal for the log file to show characters like this ?


È…p©éÇ¤FÏl/z¼hÝÌaÈE³.ÃNV‹Ú3ï:œP¦"ìqŽg36`8gIzÿ)÷Æ‰\9?Ã˜‹r–j"coq‡†{8fÌ\*Z$è¡->"Ä¦z¯.Ø–®”C‚Ë=«%#¨Å9Û,mõþ¯NS,nþ¿­Ò¡¦-ÿx8­©¶Í	¸³Ørž†Xl<3 T+ck[¨jEÒ±ÌÝ–%(l£¶»8ë¨Éå"ÅF¬•gûîìOpHëØ¿¿¾.m†ê¯}}¿b¾Ç˜”ë ÿBmpé¥O {;»•‘ƒ&_Às = 0x0564 flags = 0x0000 len =

**Comment by Demion** [comment] 2018-04-26 18:04
```
**Starting from claymore 11.1 and phoenix 2.7c not supported because of SSL.** 
More details here - https://github.com/Demion/nodevfee/issues/34#issuecomment-370114352
```
